myproject/gestorbases/urls.py
from django.contrib import admin
from django.urls import path
from myproject.gestorbases import views

app_name='gestorbases'

urlpatterns = [
	#path('', views.home, name='home'),
	path('', views.dashboard, name='dashboard'),


	path('bases/nova', views.BaseCreateView.as_view(), name='nova_base'),
	#path('bases/lista', views.BaseListView.as_view(), name='lista_bases'),
	path('bases/lista', views.listingBases, name='lista_bases'),
	path('bases/atualiza/<pk>', views.BaseUpdateView.as_view(), name='atualiza_base'),
	path('bases/exclui/<pk>', views.BaseDeleteView.as_view(), name='exclui_base'),


	path('tabelas/nova', views.TabelaCreateView.as_view(), name='nova_tabela'),
	#path('tabelas/lista', views.TabelaListView.as_view(), name='lista_tabelas'),
	path('tabelas/lista', views.listingTables, name='lista_tabelas'),
	path('tabelas/atualiza/<pk>', views.TabelaUpdateView.as_view(), name='atualiza_tabela'),
	path('tabelas/exclui/<pk>', views.TabelaDeleteView.as_view(), name='exclui_tabela'),


	#path('atualizacoes/nova', views.AtualizacaoCreateView.as_view(), name='nova_atualizacao'),
	path('atualizacoes/nova2/<pk>,<tab_nome>', views.novaAtualizazao, name='nova_atualizacao2'),
	path('atualizacoes/nova/<pk>', views.AtualizacaoCreateView2.as_view(), name='nova_atualizacao3'),

	#path('atualizacoes/lista', views.AtualizacaoListView.as_view(), name='lista_atualizacoes'),
	path('atualizacoes/lista', views.listingAtualizacoes, name='lista_atualizacoes'),
	path('atualizacoes/detalhes/<pk>', views.AtualizacaoDetalhesView.as_view(), name='detalhes_atualizacao'),
	path('atualizacoes/atualiza/<pk>', views.AtualizacaoUpdateView.as_view(), name='atualiza_atualizacao'),
	path('atualizacoes/exclui/<pk>', views.AtualizacaoDeleteView.as_view(), name='exclui_atualizacao'),

	path('atualizacoes/chart', views.getAtualizacoes, name='atualizacoes_chart'),

	path('login/', views.login, name='login'),
	path('sair/', views.sair, name='sair'),

    path('admin/', admin.site.urls),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('core/', include('myproject.core.urls', namespace='core')),

    path('website/', include('myproject.website.urls', namespace='website')),

    path('gestorbases/', include('myproject.gestorbases.urls', namespace='gestorbases'))
]

myproject/website/urls.py
from myproject.website.views import IndexTemplateView, FuncionarioListView, FuncionarioUpdateView, FuncionarioCreateView, \
    FuncionarioDeleteView

from django.urls import path

from myproject.website import views

app_name = 'website'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    #path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    path('funcionarios/', views.listing, name='lista_funcionarios'),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),
]

myproject/gestorbases/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Base(models.Model):
    nome = models.CharField(max_length=255, null=False, blank=False)
    descricao = models.TextField(null=True, blank=False)
    atualizacao = models.DateField('Data de atualizacao', null=True, blank=True)
    host = models.CharField(max_length=255, null=True, blank=False)
    owner = models.CharField(max_length=255, null=True, blank=True)
    objetos = models.Manager()

    def __str__(self):
        return self.nome


class Tabela(models.Model):
    base = models.ForeignKey(Base, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, null=True, blank=False)
    descricao = models.TextField(max_length=255, null=True, blank=True)
    esquema = models.CharField(max_length=255, null=True, blank=True)
    objetos = models.Manager()

    def __str__(self):
        return self.nome
     


class Atualizacao(models.Model):
    tabela = models.ForeignKey(Tabela, on_delete=models.CASCADE)
    data_atualizacao = models.DateField('Data da atualizacao', auto_now_add=True)
    responsavel = models.CharField(max_length=255, null=False, blank=False)
    observacoes = models.TextField(null=True, blank=True)
    mes_ref = models.IntegerField(null=True, blank=True)
    ano_ref = models.IntegerField(null=True, blank=True)
    origem_dados = models.CharField(max_length=255, null=True, blank=False)
    objetos = models.Manager()

    def __str__(self):
        return self.tabela.nome

      

myproject/gestorbases/forms.py
from django import forms
from myproject.gestorbases.models import Base, Tabela , Atualizacao


# FORMULÁRIO DE INCLUSÃO DE BASES
# -------------------------------------------
class InsereBaseForm(forms.ModelForm):
	
	class Meta:
		# Modelo 
		model = Base
		# Campos que estarão no form
		fields = ['nome', 'descricao', 'atualizacao', 'host', 'owner']


class InsereTabelaForm(forms.ModelForm):
    class Meta:
        # Modelo
        model = Tabela
        # Campos que estarão no form
        fields = ['base', 'nome', 'descricao', 'esquema']


class InsereAtualizacaoForm(forms.ModelForm):
    class Meta:
        # Modelo
        model = Atualizacao
        # Campos que estarão no fomr
        fields = ['tabela', 'responsavel', 'observacoes', 'mes_ref', 'ano_ref', 'origem_dados']


    def filteringTables(request):
        tabela = request.GET.get('tabela')
        tabelas = Tabela.objetos.filter(nome__icontains=tabela)
        return tabelas

        

myproject/gestorbases/views.py
# DEPENDÊNCIAS NECESSÁRIAS PARA REDIRECIONAR E RENDERIZAR TEMPLATES
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.shortcuts import render
from django.http import HttpResponse


# DEPENDÊNCIAS NECESSÁRIAS PARA TEMPLATES
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import View

# IMPORTANDO OS FORMS DA APLICAÇÃO
from myproject.gestorbases.forms import InsereBaseForm
from myproject.gestorbases.forms import InsereTabelaForm
from myproject.gestorbases.forms import InsereAtualizacaoForm

# IMPORTANDO OS MODELS DA APLICAÇÃO
from myproject.gestorbases.models import Base
from myproject.gestorbases.models import Tabela
from myproject.gestorbases.models import Atualizacao

# DEPENDÊNCIAS NECESSÁRIAS PARA IMPLEMENTAR A PAGINAÇÃO
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.core.paginator import Paginator

# DEPENDÊNCIAS NECESSÁRIAS PARA IMPLEMENTAR A LOGIN
from django.contrib.auth import authenticate, logout, login as authlogin
from django.shortcuts import render_to_response
from django.template import Context, loader, RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

# DEPENDÊNCIAS NECESSÁRIAS PARA SERIALIZAR DADOS EM JSON
import json



# ########################### VIEWS DE LOGIN ##########################
def login(request):
	if request.user.id:
		return render(request, 'gestorbases/logado.html',{})
	if request.POST:
		usuario = request.POST.get('usuario')
		senha = request.POST.get('senha')
		u = authenticate(request, username=usuario, password=senha)

		if(u is not None):
			if(u.is_active):
				authlogin(request, u)
				return redirect('gestorbases:dashboard')
				#return render(request, 'gestorbases/dashboard.html',{'user': u})
	return render(request, 'gestorbases/login.html', {})

def sair(request):
	logout(request)
	return render(request, 'gestorbases/login.html', {})
# ########################### SISTEMA DE LOGIN ##########################


# RENDERIZAR O DASHBOARD
@login_required
def dashboard(request):
	if request.user.is_authenticated:
		bases = Base.objetos.all()
		tabelas = Tabela.objetos.all()
		atualizacoes = Atualizacao.objetos.all()
		contexto = {'tabelas': tabelas, 'bases': bases, 'atualizacoes': atualizacoes}
		return render(request, 'gestorbases/dashboard.html', contexto)


# CADASTRAMENTO DE BASE
# ----------------------------------------------
class BaseCreateView(LoginRequiredMixin, CreateView):
    template_name = 'gestorbases/base/cadastroBase.html'
    model = Base
    form_class = InsereBaseForm
    success_url = reverse_lazy("gestorbases:lista_bases")



# LISTAGEM DE BASES COM PAGINAÇÃO
# ----------------------------------------------
@login_required
def listingBases(request):
	bases_lista = Base.objetos.all().order_by('id')
	paginator = Paginator(bases_lista, 7)
	page = request.GET.get('page')
	bases = paginator.get_page(page)
	return render(request, 'gestorbases/base/listaBases.html', {'bases':bases})

# ATUALIZAÇÃO DE BASE
# ----------------------------------------------
class BaseUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'gestorbases/base/editaBase.html'
	model = Base
	fields = '__all__'
	context_object_name = 'base'
	success_url = reverse_lazy("gestorbases:lista_bases")


# EXCLUSÃO DE BASE
# ----------------------------------------------
class BaseDeleteView(LoginRequiredMixin, DeleteView):
	template_name = 'gestorbases/base/excluiBase.html'
	model = Base
	fields = '__all__'
	context_object_name = 'base'
	success_url = reverse_lazy('gestorbases:lista_bases')



# CADASTRO DE TABELA
# ----------------------------------------------
class TabelaCreateView(LoginRequiredMixin, CreateView):
	template_name = 'gestorbases/tabela/cadastroTabela.html'
	model = Tabela
	form_class = InsereTabelaForm
	success_url = reverse_lazy('gestorbases:lista_tabelas')


# LISTAGEM DE TABELAS COM PAGINAÇÃO
# ----------------------------------------------
@login_required
def listingTables(request):
	if request.GET.get('tabela') == None:
		tabelas_lista = Tabela.objetos.all()[:100]
		paginator = Paginator(tabelas_lista, 7)
		page = request.GET.get('page')
		tabelas = paginator.get_page(page)
		return render(request, 'gestorbases/tabela/listaTabelas.html', {'tabelas': tabelas})
	else:
		tab = request.GET.get('tabela')
		tabelas_lista = Tabela.objetos.filter(nome__icontains=tab)[:100]
		paginator = Paginator(tabelas_lista, 7)
		page = request.GET.get('page')
		tabelas = paginator.get_page(page)
		return render(request, 'gestorbases/tabela/listaTabelas.html', {'tabelas': tabelas})



# EDIÇÃO DE TABELAS
# ----------------------------------------------
class TabelaUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'gestorbases/tabela/editaTabela.html'
	models = Tabela
	fields = '__all__'
	context_object_name = 'tabela'
	success_url = reverse_lazy('gestorbases:lista_tabelas')


	def get_object(self, queryset=None):
		tabela = None
		id = self.kwargs.get(self.pk_url_kwarg)
		if id is not None:
			# Busca o tabela apartir do id
			tabela = Tabela.objetos.filter(id=id).first()

		# Retorna o objeto encontrado
		return tabela
		

# EXCLUSÃO DE TABELA
# ----------------------------------------------
class TabelaDeleteView(LoginRequiredMixin, DeleteView):
	template_name = 'gestorbases/tabela/excluiTabela.html'
	model = Tabela
	fields = '__all__'
	context_object_name = 'tabela'
	success_url = reverse_lazy('gestorbases:lista_tabelas')



# REGISTRO DE NOVA ATUALIZAÇÃO
# ----------------------------------------------

class AtualizacaoCreateView(LoginRequiredMixin, CreateView):
	template_name = 'gestorbases/atualizacao/cadastroAtualizacao.html'
	model = Atualizacao
	InsereAtualizacaoForm.tabela = Tabela.objetos.all()[:5]
	form_class = InsereAtualizacaoForm
	success_url = reverse_lazy('gestorbases:nova_atualizacao')



def novaAtualizazao(request, pk, tab_nome):
	if request.POST:
		tabela_id = request.POST.get('tabela')
		tabela = Tabela.objetos.filter(id=tabela_id).first()
		responsavel = request.POST.get('responsavel')
		origem_dados = request.POST.get('origem_dados')
		mes_ref = request.POST.get('mes_ref')
		ano_ref = request.POST.get('ano_ref')
		observacao = request.POST.get('observacao')
		atualizacao = Atualizacao(tabela=tabela, responsavel=responsavel, observacoes=observacao, mes_ref=mes_ref, ano_ref=ano_ref, origem_dados=origem_dados)
		atualizacao.save()
		return redirect('gestorbases:lista_atualizacoes')
	else:
		context = {
			'tabela': tab_nome, 'pk':pk
		}
		return render(request, 'gestorbases/atualizacao/novaAtualizacao.html', context)

class AtualizacaoCreateView2(LoginRequiredMixin, CreateView):
	template_name = 'gestorbases/atualizacao/novaAtualizacao.html'
	model = Atualizacao
	InsereAtualizacaoForm.tabela = Tabela.objetos.all()[:5]
	form_class = InsereAtualizacaoForm
	success_url = reverse_lazy('gestorbases:nova_atualizacao')

	def get_object(self, queryset=None):
		tabela = None
		id = self.kwargs.get(self.pk_url_kwarg)
		if id is not None:
			tabela = Tabela.objetos.filter(id=id).first()
		return tabela


# FAZ PAGINAÇÃO DE ATUALIZAÇÃO
# ----------------------------------------------
@login_required
def listingAtualizacoes(request):
	if request.GET.get('tabela') != None and request.GET.get('data') != None:
		tab = request.GET.get('tabela')
		date = request.GET.get('data')
		atualizacoes = getUpdateByTableAndDate(request, tab, date)
		contexto = {'atualizacoes': atualizacoes, 'nomeTabela':tab, 'data':date}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	elif request.GET.get('tabela') != None:
		tab = request.GET.get('tabela')
		atualizacoes = getUpdateByTables(request, tab)
		contexto = {'atualizacoes': atualizacoes, 'nomeTabela':tab}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	elif request.GET.get('tabela') == None:		
		atualizacoes = getAllUpdates(request)
		contexto = {'atualizacoes': atualizacoes}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	else:
		tab = request.GET.get('tabela')
		date = request.GET.get('data')
		atualizacoes = getUpdateByTableAndDate(request, tab, date)
		#atualizacoes = getUpdateByTables(request, tab)
		contexto = {'atualizacoes': atualizacoes, 'nomeTabela':tab, 'data':date}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	

def getAllUpdates(request):
	atualizacoes_lista = Atualizacao.objetos.all().order_by('pk')
	paginator = Paginator(atualizacoes_lista, 5)
	page = request.GET.get('page')
	return paginator.get_page(page)

def getUpdateByTables(request, tab):
	tabelas = Tabela.objetos.filter(nome__icontains=tab)
	condicao = ''
	for tabela in tabelas:
		if condicao != '':
			condicao = condicao + ', ' + str(tabela.id)
		else:
			condicao = condicao + str(tabela.id)
	condicao = "(" + condicao + ")"
	if condicao == '()':
		condicao = '(-1)'
	atualizacoes_lista = Atualizacao.objetos.raw("select * from gestorbases_atualizacao where tabela_id in " + condicao)
	paginator = Paginator(atualizacoes_lista, 5)
	page = request.GET.get('page')
	return paginator.get_page(page)



def getAtualizacoes(request):
	from django.db import connection
	atualizacoes = []
	cursor = connection.cursor()
	cursor.execute("select to_char(data_atualizacao, 'DD/MM/yyyy'), count(*) from gestorbases_atualizacao where data_atualizacao > current_date - INTERVAL '365 DAYS' group by data_atualizacao order by data_atualizacao")
	for atualizacao in cursor:
		atualizacoes.append(atualizacao)


	if request.is_ajax():
		contexto = {'atualizacoes':atualizacoes}

myproject/gestorbases/templates/gestorbases/editaAluno.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<form method="post" action="">
	  {% csrf_token %}

	  <label for="{{ form.matricula.id_for_label }}">Matricula</label>
	  {{ form.matricula }}

	  <label for="{{ form.nome.id_for_label }}">Nome</label>
	  {{ form.nome }}

	  <label for="{{ form.nome_mae.id_for_label }}">Nome da mãe</label>
	  {{ form.nome_mae }}

	  <button type="submit">Cadastrar</button>
	</form>

</body>
</html>

myproject/gestorbases/templates/gestorbases/excluiBase.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}


{% load static %}

{% block titulo_conteudo %}Excluir Base {% endblock %}

{% block opcoes %}
    
{% endblock %}

{% block conteudo %}

    <div class="card" style="border: 1px solid #1E94D2;
        								border-radius: 5px;
        								padding: 2%; box-shadow: 5px 5px 8px #888888;">
      <div class="card-body">
        <h5 class="card-title" style="font-weight: bold;">Tem certeza que quer excluir esta base?</h5>
        <hr />
        <div class="form-group" style="border-radius: 5px;
        								padding: 2%;  ">
          <label for="input-base-nome">Nome</label>
          {{base.nome}}
          <br/>
          <label for="input-base-nome">Descrição</label>
          {{base.descricao}}
          <br/>
          <label for="input-base-nome">Host</label>
          {{base.host}}
          <br/>
          <label for="input-base-nome">Owner</label>
          {{base.owner}}
        </div>
      </div>

      <form method="post">
          {% csrf_token %}
          <hr />
          <div class="text-right">
            <a href="{% url 'gestorbases:lista_funcionarios' %}" 
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
    </div>


<!-- 
    <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Funcionário</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o funcionário 
          <b>{{ funcionario.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_funcionarios' %}" 
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  -->
{% endblock %}

myproject/gestorbases/templates/gestorbases/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'gestorbases/assets/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'gestorbases/assets/stylesheets/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'gestorbases/assets/stylesheets/vendors.min.css' %}">

<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>
	<h1>Home page</h1>
	<br>
	<br>
	<a href="{% url 'gestorbases:nova_base' %}">Nova Base</a>

	<div class="table-responsive" ">
		
		<table class="table" ">
			<tr>
				<th>Matrícula</th>
				<th>Nome</th>
				<th>Nome da mãe</th>
			</tr>
			{% for aluno in alunos %}
		  	<tr>
		    	<td>{{ aluno.matricula }}</td>
			    <td>{{ aluno.nome }}</td> 
			    <td>{{ aluno.nome_mae }}</td>
		  	</tr>
		  	{% endfor %}
		</table>
	</div>

</body>
</html>

myproject/gestorbases/templates/gestorbases/listaBases.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}


{% load static %}

{% block titulo_conteudo %}Lista de Bases {% endblock %}

{% block opcoes %}
	
{% endblock %}

{% block conteudo %}

	<div class="container-fluid">

		<div class="table-responsive">
			{% if bases|length > 0 %}
				<table id="tabela-produtos" class="table  table-striped  table-bordered  table-hover  table-condensed  js-sticky-table">
					<thead class="aw-table-header-dark"><!--thead-dark-->
						<tr>
							<th class="text-center">Id</th>
							<th>Nome</th>
							<th>Descrição</th>
							<th>Host</th>
							<th>Owner</th>
							<th class="text-center">Editar</th>
							<th class="text-center">Excluir</th>
						</tr>
					</thead>
				  
					<tbody>
						{% for base in bases %}
							<tr >
								<td class="text-center">{{base.id}}</td>

								<td>
									<a href="#">{{base.nome}}</a>
								</td>

								<td >{{base.descricao}}</td>

								<td class="text-right">{{base.host}}</td>

								<td class="text-right">{{base.owner}}</td>

								<td class="text-center">
									<a href="{% url 'gestorbases:atualiza_base' pk=base.id %}" class="btn btn-info btn-xs"><span class="fa fa-edit"></span>
							        </a>
							    </td>

							    <td class="text-center">
									<!--<button type="button" class="btn btn-danger btn-xs"> <!--onclick="excluir()"-->
										<a href="{% url 'gestorbases:exclui_base' pk=base.id %}" class="btn btn-danger btn-xs">
										<span class="fa fa-trash" ></span>
										</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			{% else %}
                <div class="text-center mt-5 mb-5 jumbotron">
                   <h5>Nenhuma <code>Base</code> cadastrada ainda.</h5>
                </div>
            {% endif %}
		</div>
		<div> <!-- class="text-right" -->
        <a href="{% url 'gestorbases:nova_base' %}" class="btn btn-primary">
          Nova Base
        </a>
    </div>
	</div>
	<script>
	function excluir() {
		swal({
			title: "Tem certeza?",
			text: "Você não poderá recuperar este registro após a exclusão.",
			type: "warning",
			showCancelButton: true,
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "Sim, exclua agora!",
			closeOnConfirm: false,
			showLoaderOnConfirm: true
		}, function() {
			setTimeout(function() {
				swal("Excluído!", "O registro foi excluído com sucesso.", "success");
			}, 2000);
		});
	}
	</script>
{% endblock %}

myproject/gestorbases/templates/gestorbases/logado.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}


{% load static %}

{% block titulo_conteudo %}Dashboard{% endblock %}

{% block conteudo %}
  <div id="container">
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
  <script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Historic World Population by Region'
        },
        xAxis: {
            categories: ['Africa', 'America', 'Asia', 'Europe', 'Oceania']
        },
        series: [{
            name: 'Year 1800',
            data: [107, 31, 635, 203, 2]
        }, {
            name: 'Year 1900',
            data: [133, 156, 947, 408, 6]
        }, {
            name: 'Year 2012',
            data: [1052, 954, 4250, 740, 38]
        }]
    });
  </script>
  </div>
{% endblock %}

myproject/gestorbases/templates/gestorbases/teste.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}


{% load static %}

{% block titulo_conteudo %}Teste de listagem de tabelas {% endblock %}

{% block opcoes %}
    
{% endblock %}

{% block conteudo %}
	
    <div class="row-fluid">
        <form name="form1" id="form_search" method="GET" action="{% url 'gestorbases:teste2' %}" class="form-signin">
        
        <div class="col-lg-3">
            <input type="text" name="tabela" id="tabela" class="form-control" placeholder="tabela" autofocus>
        </div>
                
        <div class="col-lg-2">
            <button class="btn btn-primary" type="submit">Buscar</button>
        </div>
        </form><!-- /form -->
        <br>
    </div><!-- /card-container -->
    

    <div class="container-fluid">

        <div class="table-responsive">
            {% if tabelas|length > 0 %}
                <table id="tabela-produtos" class="table  table-striped  table-bordered  table-hover  table-condensed  js-sticky-table">
                    <thead class="aw-table-header-dark"><!--thead-dark-->
                        <tr>
                            <th>Base</th>
                            <th>Tabela</th>
                            <th>Descrição</th>
                            <th>Esquema</th>
                            <th class="text-center">Editar</th>
                            <th class="text-center">Excluir</th>
                        </tr>
                    </thead>
                  
                    <tbody>
                        {% for tabela in tabelas %}
                            <tr >
                                <td class="text-center">{{tabela.base}}</td>

                                <td>
                                    <a href="{% url 'gestorbases:atualiza_tabela' pk=tabela.id %}">{{tabela.nome}}</a>
                                </td>

                                <td >{{tabela.descricao}}</td>

                                <td class="text-right">{{tabela.esquema}}</td>


                                <td class="text-center">
                                    <a href="{% url 'gestorbases:atualiza_tabela' pk=tabela.id %}" class="btn btn-info btn-xs"><span class="fa fa-edit"></span>
                                    </a>
                                </td>

                                <td class="text-center">
                                    <!--<button type="button" class="btn btn-danger btn-xs">--> <!--onclick="excluir()"-->
                                        <a href="{% url 'gestorbases:exclui_tabela' pk=tabela.id %}" class="btn btn-danger btn-xs">
                                        <span class="fa fa-trash" ></span>
                                        </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="text-center mt-5 mb-5 jumbotron">
                   <h5>Nenhuma <code>Base</code> cadastrada ainda.</h5>
                </div>
            {% endif %}
        </div>
        <div> <!-- class="text-right" -->
            <a href="{% url 'gestorbases:nova_base' %}" class="btn btn-primary">
            Nova Base
            </a>
        </div>
    </div>

{%  endblock%}

<!-- Bloco de scripts -->
{% block scripts %}
 <script>
    
    $("#tabela").keyup(function() {
        console.log($('#tabela').val());
        $('#form_search').submit(function(e){
            e.preventDefault();

            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),

                success: function(data){
                    console.log(data);
                }

            })


            alert('form submited!!' + $(this).attr('action'));
        })
        /*
        $.ajax({
            var tabela = $('#tabela').val();
            alert( "Tabela: " + tabela );
            url : "{% url 'gestorbases:teste' %}",
            type : 'post',
            data : {
                tabela : tabela,
            },
          
        })
        */

    });
  </script>
<!--
    <script>
    $("#id_username").change(function () {
      var form = $(this).closest("form");
      $.ajax({
        url: form.attr("data-validate-username-url"),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
          }
        }
      });

    });
  </script>
-->

{% endblock %}