myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('core/', include('myproject.core.urls', namespace='core')),

    path('website/', include('myproject.website.urls', namespace='website')),

    path('gestorbases/', include('myproject.gestorbases.urls', namespace='gestorbases'))
]

myproject/website/urls.py
from myproject.website.views import IndexTemplateView, FuncionarioListView, FuncionarioUpdateView, FuncionarioCreateView, \
    FuncionarioDeleteView

from django.urls import path

from myproject.website import views

app_name = 'website'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    #path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    path('funcionarios/', views.listing, name='lista_funcionarios'),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),
]

myproject/website/forms.py
from django import forms
from myproject.models import Funcionario



# FORMULÁRIO DE INCLUSÃO DE FUNCIONÁRIOS
# -------------------------------------------

class InsereFuncionarioForm(forms.ModelForm):

    chefe = forms.BooleanField(
        label='Chefe?',
        required=False,
    )

    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    class Meta:
        # Modelo base
        model = Funcionario

        # Campos que estarão no form
        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'tempo_de_servico',
            'remuneracao'
        ]

myproject/website/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from myproject.models import Funcionario
from myproject.website.forms import InsereFuncionarioForm

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render


# PÁGINA PRINCIPAL
# ----------------------------------------------
class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioListView(ListView):
    template_name = "website/lista.html"
    model = Funcionario
    context_object_name = "funcionarios"


# CADASTRAMENTO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioCreateView(CreateView):
    template_name = "website/cria.html"
    model = Funcionario
    form_class = InsereFuncionarioForm
    success_url = reverse_lazy("website:lista_funcionarios")


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("website:lista_funcionarios")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("website:lista_funcionarios")



# PAGINAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------
def listing(request):
    funcionarios_list = Funcionario.objetos.all()
    paginator = Paginator(funcionarios_list, 2) # Exibe dois funcionários por página
    page = request.GET.get('page')
    funcionarios = paginator.get_page(page)
    return render(request, 'website/lista2.html', {'funcionarios': funcionarios})

myproject/website/templates/website/atualiza.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Dados do Funcionários{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualização de Dados do Funcionário</h5>          
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- CPF -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CPF</span>
              </div>
              {% render_field form.cpf class+="form-control" %}
            </div>

            <!-- Tempo de Serviço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Tempo de Serviço</span>
              </div>
              {% render_field form.tempo_de_servico class+="form-control" %}
            </div>

            <!-- Remuneração -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Remuneração</span>
              </div>
              {% render_field form.remuneracao class+="form-control" %}
            </div>

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myproject/website/templates/website/cria.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Funcionários{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Funcionário</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            um novo <code>Funcionário</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- CPF -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CPF</span>
              </div>
              {% render_field form.cpf class+="form-control" %}
            </div>

            <!-- Tempo de Serviço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Tempo de Serviço</span>
              </div>
              {% render_field form.tempo_de_servico class+="form-control" %}
            </div>

            <!-- Remuneração -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Remuneração</span>
              </div>
              {% render_field form.remuneracao class+="form-control" %}
            </div>

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myproject/website/templates/website/exclui.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Funcionário</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o funcionário 
          <b>{{ funcionario.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_funcionarios' %}" 
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

myproject/website/templates/website/index.html
<!-- Estendemos do template base -->
{% extends 'website/_layouts/base.html' %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Funcionário</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Funcionário</code>.
          </p>
          <a href="{% url 'website:cadastra_funcionario' %}"
             class="btn btn-primary">
            Novo Funcionário
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Funcionários</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Funcionários</code> cadastrados.
          </p>
          <a href="{% url 'website:lista_funcionarios' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Funcionário</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Funcionário</code>.
          </p>
          <a href="{% url 'website:cadastra_funcionario' %}"
             class="btn btn-primary">
            Novo Funcionário
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Funcionários</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Funcionários</code> cadastrados.
          </p>
          <a href="{% url 'website:lista_funcionarios' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myproject/website/templates/website/lista.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Funcionários{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
            <h5 class="card-title">Lista de Funcionário</h5>

            {% if funcionarios|length > 0 %}
                <p class="card-text">
                  Aqui está a lista de <code>Funcionários</code> cadastrados.
                </p>

                <table class="table">
                  <thead class="thead-dark">
                  <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Sobrenome</th>
                    <th>Tempo de Serviço</th>
                    <th>Remuneração</th>
                    <th>Ações</th>
                  </tr>
                  </thead>

                  <tbody>
                  {% for funcionario in funcionarios %}
                    <tr>
                      <td>{{ funcionario.id }}</td>
                      <td>{{ funcionario.nome }}</td>
                      <td>{{ funcionario.sobrenome }}</td>
                      <td>{{ funcionario.tempo_de_servico }}</td>
                      <td>{{ funcionario.remuneracao }}</td>
                      <td>
                        <a href="{% url 'website:atualiza_funcionario' pk=funcionario.id %}"
                           class="btn btn-info">
                          Atualizar
                        </a>
                        <a href="{% url 'website:deleta_funcionario' pk=funcionario.id %}"
                          class="btn btn-outline-danger">
                            Excluir
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            {% else %}
                <div class="text-center mt-5 mb-5 jumbotron">
                   <h5>Nenhum <code>Funcionário</code> cadastrado ainda.</h5>
                </div>
            {% endif %}
            <hr />
            <div class="text-right">
                <a href="{% url 'website:cadastra_funcionario' %}" class="btn btn-primary">
                  Cadastrar Funcionário
                </a>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myproject/website/templates/website/lista2.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Funcionários{% endblock %}

{% block conteudo %}

<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
            <h5 class="card-title">Lista de Funcionário</h5>

            {% if funcionarios|length > 0 %}
                <p class="card-text">
                  Aqui está a lista de <code>Funcionários</code> cadastrados.
                </p>

                <table class="table">
                  <thead class="thead-dark">
                  <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Sobrenome</th>
                    <th>Tempo de Serviço</th>
                    <th>Remuneração</th>
                    <th>Ações</th>
                  </tr>
                  </thead>

                  <tbody>
                  {% for funcionario in funcionarios %}
                    <tr>
                      <td>{{ funcionario.id }}</td>
                      <td>{{ funcionario.nome }}</td>
                      <td>{{ funcionario.sobrenome }}</td>
                      <td>{{ funcionario.tempo_de_servico }}</td>
                      <td>{{ funcionario.remuneracao }}</td>
                      <td>
                        <a href="{% url 'website:atualiza_funcionario' pk=funcionario.id %}"
                           class="btn btn-info">
                          Atualizar
                        </a>
                        <a href="{% url 'website:deleta_funcionario' pk=funcionario.id %}"
                          class="btn btn-outline-danger">
                            Excluir
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            {% else %}
                <div class="text-center mt-5 mb-5 jumbotron">
                   <h5>Nenhum <code>Funcionário</code> cadastrado ainda.</h5>
                </div>
            {% endif %}
            <hr />
            <div class="text-right">
                <a href="{% url 'website:cadastra_funcionario' %}" class="btn btn-primary">
                  Cadastrar Funcionário
                </a>
            </div>

            <!-- CONTROLES DE NAVEGAÇÃO -->
            <div class="pagination">
			    <span class="step-links">
			        {% if funcionarios.has_previous %}
			            <a href="?page=1">&laquo; first</a>
			            <a href="?page={{ funcionarios.previous_page_number }}">previous</a>
			        {% endif %}

			        <span class="current">
			            Page {{ funcionarios.number }} of {{ funcionarios.paginator.num_pages }}.
			        </span>

			        {% if funcionarios.has_next %}
			            <a href="?page={{ funcionarios.next_page_number }}">next</a>
			            <a href="?page={{ funcionarios.paginator.num_pages }}">last &raquo;</a>
			        {% endif %}
			    </span>
			</div>
			<!-- CONTROLES DE NAVEGAÇÃO -->
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}